In [ ]:
import numpy as np

In [ ]:
scores = np.array([45, 67, 89, 34, 90, 56, 77, 23, 61, 48])
print("All Scores:", scores)
print("Scores > 50:", scores[scores > 50])

All Scores: [45 67 89 34 90 56 77 23 61 48]
Scores > 50: [67 89 90 56 77 61]


In [ ]:
print("Mean Score:", np.mean(scores))

Mean Score: 59.0


In [ ]:
print("Median Score:", np.median(scores))

Median Score: 58.5


In [ ]:
from scipy import stats

mode_result = stats.mode(scores, keepdims=True)
print("Mode Score:", mode_result.mode[0])

Mode Score: 23


In [ ]:
temps = np.array([
    [30, 32, 31, 29, 35, 36, 34],
    [33, 34, 32, 31, 30, 29, 28],
    [36, 35, 34, 33, 32, 31, 30],
    [29, 28, 30, 31, 32, 33, 34]
])
print("Temperature Array:\n", temps)
print("Week 2 Temps:", temps[1])

Temperature Array:
 [[30 32 31 29 35 36 34]
 [33 34 32 31 30 29 28]
 [36 35 34 33 32 31 30]
 [29 28 30 31 32 33 34]]
Week 2 Temps: [33 34 32 31 30 29 28]


In [ ]:
print("Max Temperature:", np.max(temps))

Max Temperature: 36


In [ ]:
min_temp = np.min(temps)
max_temp = np.max(temps)
normalized = (temps - min_temp) / (max_temp - min_temp)
print("Normalized Temps:\n", normalized)

Normalized Temps:
 [[0.25  0.5   0.375 0.125 0.875 1.    0.75 ]
 [0.625 0.75  0.5   0.375 0.25  0.125 0.   ]
 [1.    0.875 0.75  0.625 0.5   0.375 0.25 ]
 [0.125 0.    0.25  0.375 0.5   0.625 0.75 ]]


In [ ]:
print("Standard Deviation:", np.std(temps))

Standard Deviation: 2.294625486315573


In [ ]:
stock = np.random.randint(10, 100, size=(4, 3, 5))
print("2nd Product in Week 3 Stock:", stock[2, 1])

2nd Product in Week 3 Stock: [79 17 93 63 87]


In [ ]:
total_per_product = np.sum(stock, axis=(0, 2))
print("Total Stock per Product:", total_per_product)

Total Stock per Product: [1225 1147 1234]


In [ ]:
ratings = np.random.randint(1, 11, 50)
print("Ratings > 7:", np.sum(ratings > 7))

Ratings > 7: 11


In [ ]:
print("Neutral Ratings (==5):", np.sum(ratings == 5))

Neutral Ratings (==5): 6


In [ ]:
norm_ratings = (ratings - np.min(ratings)) / (np.max(ratings) - np.min(ratings))
print("Normalized Ratings:\n", norm_ratings)

Normalized Ratings:
 [0.66666667 0.77777778 0.55555556 0.22222222 0.11111111 0.44444444
 0.11111111 0.44444444 1.         0.44444444 0.88888889 0.66666667
 0.88888889 0.55555556 0.77777778 0.         0.11111111 0.44444444
 0.22222222 0.88888889 0.33333333 0.         0.33333333 0.66666667
 0.22222222 0.88888889 0.22222222 0.66666667 0.66666667 0.33333333
 0.11111111 0.22222222 0.         0.11111111 0.66666667 1.
 0.33333333 0.77777778 0.44444444 0.11111111 0.77777778 1.
 0.33333333 0.66666667 0.44444444 0.11111111 0.22222222 0.66666667
 0.22222222 0.22222222]


In [ ]:
steps = np.random.randint(4000, 10000, size=(5, 7))  # 5 users × 7 days
avg_steps = np.mean(steps, axis=1)
print("Avg Steps/User:", avg_steps)

Avg Steps/User: [8151.         7080.71428571 6646.14285714 6351.42857143 7054.85714286]


In [ ]:
print("Steps on Day 3:", steps[:, 2])

Steps on Day 3: [9562 9451 6439 5523 9303]


In [ ]:
active_users = np.any(steps > 7000, axis=1)
print("Users walked >7000 steps:", active_users)

Users walked >7000 steps: [ True  True  True  True  True]


In [ ]:
chem_trials = np.random.rand(10, 3) * 100
mean_per_chemical = np.mean(chem_trials, axis=0)
print("Mean per Chemical:", mean_per_chemical)

Mean per Chemical: [35.93161154 44.24777797 59.67222308]


In [ ]:
deviation = np.abs(chem_trials - np.mean(chem_trials, axis=0))
max_dev_trial = np.argmax(deviation, axis=0)
print("Trial with max deviation:", max_dev_trial)

Trial with max deviation: [5 4 5]


In [ ]:
vitals = np.random.rand(2, 5, 3) * 100
print("Patient 1, Day 4 Vitals:", vitals[0, 3])

Patient 1, Day 4 Vitals: [24.89865874 55.51784929  3.9566255 ]


In [ ]:
vital_values = vitals[0, :, 1]
vital_mode = stats.mode(vital_values, keepdims=True)
print("Mode of Vital Sign 1 for Patient 0:", vital_mode.mode[0])

Mode of Vital Sign 1 for Patient 0: 14.72842757510675
